{% set name = "waveorder" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/waveorder-{{ version }}.tar.gz
  sha256: 23d8428b59339049f13ac13d9f2f705ffab193a718d8d5cf302708ae58e6595f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - ipython
    - ipywidgets >=7.5.1
    - matplotlib-base >=3.1.1
    - natsort >=7.1.1
    - numpy >=1.21
    - pycromanager >=0.13.2
    - python >={{ python_min }}
    - pywavelets >=1.1.1
    - scipy >=1.3.0
    - tifffile >=2021.11.2
    - zarr >=2.6.1

test:
  imports:
    - waveorder
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/waveorder
  summary: wave optical simulations and deconvolution of optical properties
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/mehta-lab/waveorder

extra:
  recipe-maintainers:
    - talonchandler
    - mattersoflight
    - goanpeca
